version: 0.2.{build}
skip_tags: true
configuration: Release
platform: Any CPU
clone_depth: 4
test: off
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
  - ps: Remove-Item packages\OpenCover* -include ("*.pdb", "*.sln", "*.csproj") -recurse
after_test: 
  - ps: .\CreateCoverage.ps1
environment:
  COVERALLS_REPO_TOKEN:
    secure: n/N6BlvDKmDfYC/qkGfkV64Kus6obdGAPBhnaIEHKRuk6FUBbnb/8/d+VkzZ+z/7
build:
  project: Dapplo.InterfaceImpl.sln
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: GitHub
  release: Dapplo.InterfaceImpl-v$(appveyor_build_version)
  auth_token:
    secure: eBQPtXg53XgcvdcVY3wQAw6kkwNh+QhcsTDwzyQLLh6IOPyiePEaEhJR0D2YBjAj
  artifact: /.*\.nupkg/
  draft: false
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: 0+4uMr/wsyh8BisfHCwkDbaWwzmKNvvB2MwFz45/ePwbOMB6WT1AfhzujeddcN/2
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
